# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-GD-Image
version:      0.02
version_from: lib/Geo/GD/Image.pm
installdirs:  site
requires:
    GD:                            2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
